### ISSUE TITLE
Fallback to pre-1.13.0 authentication when not supported

### ISSUE THREAD

**Issue by hhm0** [crustymonkey/py-sonic#17]
Some subsonic-compatible servers (for example <a href="https://github.com/spl0k/supysonic/issues/36#issuecomment-131389118">supysonic</a>) deliberately only support pre-1.13.0 authentication.

Since pre-1.13 auth is no longer works with `py-sonic` (last compatible commit was ad9d24d), it would be awesome to have py-sonic fall back to using pre-1.13.0 authentication either on authentication errors, and/or when a parameter is provided to `Connection`.

Thanks for the wonderful library!

**Comment by crustymonkey** [comment]
Yeah, I'm definitely down for making it an option.  I'm not so sure
about an automated fallback (unless it was a specific option) as I'd
rather not drop the security on people without their knowledge.

Work is super busy this week, but I'm hoping to have the time to spend
on some personal projects next week.

Thanks for the suggestion.

**Comment by crustymonkey** [comment]
@hhm0 I've added an `auth_options` branch that contains a `legacyAuth` option as a `Connection` argument.  This will use the pre-1.13.0 auth mechanism.  I've tested against my 6.0 server and it works well.  Can you pull that branch and give it a try?  If your testing looks good, I'll merge this into master.

**Comment by crustymonkey** [comment]
I've merged this into master and created a new version (0.6.1).  Feel free to re-open the task if you have issues using the new legacyAuth option.

**Comment by hhm0** [comment]
Yes, it works! Thanks so much! :-)

**Comment by mrpurplenz** [comment]
It didnt solve the problem for Ampache/subsonic. pysonic now reports the more informative error: `libsonic.errors.VersionError: Incompatible Subsonic REST protocol version. Server must upgrade.`
I have opend an issue with ampache at [https://github.com/ampache/ampache/issues/1389](url) but thought it worth while to mention and link to it here.

**Comment by crustymonkey** [comment]
Have you tried manually setting the `apiVersion` option of the Connection object?  That will change what is sent to the server.

**Comment by mrpurplenz** [comment]
Yes that worked. So the error message was comming in as a result of ampache detecting an api version incompatibility.

**Comment by crustymonkey** [comment]
Technically, the `legacyAuth` is actually 1.13.0 and earlier.  I think I would rather leave things the way they are as the `apiVersion` override is simple and pretty straightforward to use.

As an alternative, and I think I would still make this an option, I think it would be reasonable to handle the version error where the server is lower than the client and auto set that.  The error code "30" is the mentioned error and part of the error message contains the server version.  This would be fairly easy to handle, and then force a retry.

I've opened https://github.com/crustymonkey/py-sonic/issues/19 for this issue

**Comment by metalune1** [comment]
I have a problem related to this, when trying to connect to my LMS server. It results in an error message `libsonic.errors.ParameterError: Required parameter 'p' is missing.`

**Comment by crustymonkey** [comment]
@metalune1 

>  LMS server

What is this?  Can you provide a code snippet as an example of what you are doing?

**Comment by metalune1** [comment]
oh sorry, LMS stands for Lightweight Music Server (https://github.com/epoupon/lms) but either way this is deprecated, I had to set `legacyAuth=True`

**Comment by metalune1** [comment]
yeah, it resolved my issue :)
------- Original Message -------
